
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bradey
 */
public class QRTAEntryForm extends javax.swing.JFrame {

    /**
     * Creates new form QRTAEntryForm
     */
    public QRTAEntryForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        Title = new JLabel();
        jLabel2 = new JLabel();
        vehicleEntry = new JPanel();
        addressLabel = new JLabel();
        Vehicles = new JLabel();
        numPlateLabel = new JLabel();
        modelLabel = new JLabel();
        yearLabel = new JLabel();
        ownLabel = new JLabel();
        phoneLabel = new JLabel();
        jScrollPane1 = new JScrollPane();
        modelEntry = new JTextPane();
        jScrollPane2 = new JScrollPane();
        plateEntry = new JTextPane();
        jScrollPane3 = new JScrollPane();
        ownEntry = new JTextPane();
        jScrollPane4 = new JScrollPane();
        yearEntry = new JTextPane();
        jScrollPane5 = new JScrollPane();
        addEntry = new JTextPane();
        jScrollPane6 = new JScrollPane();
        NumEntry = new JTextPane();
        newButton = new JButton();
        searchButton = new JButton();
        updateVehicle = new JButton();
        accidentPanel = new JPanel();
        jLabel1 = new JLabel();
        LocationLabel = new JLabel();
        IDLabel = new JLabel();
        NumPlateLabel = new JLabel();
        commentLabel = new JLabel();
        jScrollPane7 = new JScrollPane();
        jTextPane1 = new JTextPane();
        jScrollPane8 = new JScrollPane();
        jTextPane2 = new JTextPane();
        jScrollPane9 = new JScrollPane();
        jTextPane3 = new JTextPane();
        jScrollPane10 = new JScrollPane();
        jTextPane4 = new JTextPane();
        newAccidentButton = new JButton();
        accSearchButton = new JButton();
        NumPlateLabel1 = new JLabel();
        jScrollPane11 = new JScrollPane();
        jTextPane5 = new JTextPane();
        UpdateAccident = new JButton();
        jButton1 = new JButton();
        jScrollPane12 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jScrollPane13 = new JScrollPane();
        jTextArea2 = new JTextArea();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new Font("Tahoma", 0, 18)); // NOI18N
        Title.setHorizontalAlignment(SwingConstants.CENTER);
        Title.setText("QRTA Accident Entry Form ");
        Title.setVerticalAlignment(SwingConstants.TOP);

        vehicleEntry.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED, Color.gray, Color.lightGray, null, null));

        addressLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        addressLabel.setText("Address");

        Vehicles.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        Vehicles.setText("Vehicles");

        numPlateLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        numPlateLabel.setText("Number Plate");

        modelLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        modelLabel.setText("Model");

        yearLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        yearLabel.setText("Year");

        ownLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        ownLabel.setText("Registered Owner");

        phoneLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        phoneLabel.setText("Phone Number");

        modelEntry.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(modelEntry);

        plateEntry.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        jScrollPane2.setViewportView(plateEntry);

        ownEntry.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        jScrollPane3.setViewportView(ownEntry);

        yearEntry.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        jScrollPane4.setViewportView(yearEntry);

        addEntry.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        jScrollPane5.setViewportView(addEntry);

        NumEntry.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        jScrollPane6.setViewportView(NumEntry);

        newButton.setText("Add Vehicle");
        newButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        updateVehicle.setText("Update");
        updateVehicle.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                updateVehicleActionPerformed(evt);
            }
        });

        GroupLayout vehicleEntryLayout = new GroupLayout(vehicleEntry);
        vehicleEntry.setLayout(vehicleEntryLayout);
        vehicleEntryLayout.setHorizontalGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(vehicleEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(vehicleEntryLayout.createSequentialGroup()
                        .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(Vehicles)
                            .addComponent(ownLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modelLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numPlateLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)))
                    .addComponent(newButton)
                    .addComponent(updateVehicle)
                    .addComponent(searchButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        vehicleEntryLayout.setVerticalGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, vehicleEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(vehicleEntryLayout.createSequentialGroup()
                        .addComponent(Vehicles)
                        .addGap(10, 10, 10)
                        .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(numPlateLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(modelLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(yearLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ownLabel))
                    .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(addressLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(vehicleEntryLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(phoneLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(newButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateVehicle)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        accidentPanel.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED, Color.gray, Color.lightGray, null, null));

        jLabel1.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Accidents");

        LocationLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        LocationLabel.setText("Location");

        IDLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        IDLabel.setText("Incident ID");

        NumPlateLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        NumPlateLabel.setText("Vehicle Number Plate");

        commentLabel.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        commentLabel.setText("Comments");

        jScrollPane7.setViewportView(jTextPane1);

        jScrollPane8.setViewportView(jTextPane2);

        jScrollPane9.setViewportView(jTextPane3);

        jScrollPane10.setViewportView(jTextPane4);

        newAccidentButton.setText("Add Accident");
        newAccidentButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newAccidentButtonActionPerformed(evt);
            }
        });

        accSearchButton.setText("Search");

        NumPlateLabel1.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        NumPlateLabel1.setText("Number of Vehicles");

        jScrollPane11.setViewportView(jTextPane5);

        UpdateAccident.setText("Update");

        GroupLayout accidentPanelLayout = new GroupLayout(accidentPanel);
        accidentPanel.setLayout(accidentPanelLayout);
        accidentPanelLayout.setHorizontalGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(accidentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(accidentPanelLayout.createSequentialGroup()
                        .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(NumPlateLabel)
                            .addComponent(jLabel1)
                            .addComponent(IDLabel, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocationLabel, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                            .addComponent(commentLabel, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane10)))
                    .addGroup(accidentPanelLayout.createSequentialGroup()
                        .addComponent(NumPlateLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane11))
                    .addGroup(accidentPanelLayout.createSequentialGroup()
                        .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(newAccidentButton)
                            .addComponent(accSearchButton)
                            .addComponent(UpdateAccident))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        accidentPanelLayout.setVerticalGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(accidentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(accidentPanelLayout.createSequentialGroup()
                        .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(accidentPanelLayout.createSequentialGroup()
                                .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(IDLabel, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(LocationLabel, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(accidentPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(commentLabel, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(NumPlateLabel1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(NumPlateLabel, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(newAccidentButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateAccident)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(accSearchButton)
                .addGap(25, 25, 25))
        );

        jButton1.setBackground(Color.red);
        jButton1.setFont(new Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane12.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane13.setViewportView(jTextArea2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(384, 384, 384))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane12)
                            .addComponent(vehicleEntry, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(accidentPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane13))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(Title, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(accidentPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleEntry, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jScrollPane12))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newButtonActionPerformed

    private void searchButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void newAccidentButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newAccidentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newAccidentButtonActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateVehicleActionPerformed(ActionEvent evt) {//GEN-FIRST:event_updateVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateVehicleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QRTAEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QRTAEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QRTAEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QRTAEntryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QRTAEntryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel IDLabel;
    private JLabel LocationLabel;
    private JTextPane NumEntry;
    private JLabel NumPlateLabel;
    private JLabel NumPlateLabel1;
    private JLabel Title;
    private JButton UpdateAccident;
    private JLabel Vehicles;
    private JButton accSearchButton;
    private JPanel accidentPanel;
    private JTextPane addEntry;
    private JLabel addressLabel;
    private ButtonGroup buttonGroup1;
    private ButtonGroup buttonGroup2;
    private JLabel commentLabel;
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane10;
    private JScrollPane jScrollPane11;
    private JScrollPane jScrollPane12;
    private JScrollPane jScrollPane13;
    private JScrollPane jScrollPane2;
    private JScrollPane jScrollPane3;
    private JScrollPane jScrollPane4;
    private JScrollPane jScrollPane5;
    private JScrollPane jScrollPane6;
    private JScrollPane jScrollPane7;
    private JScrollPane jScrollPane8;
    private JScrollPane jScrollPane9;
    private JTextArea jTextArea1;
    private JTextArea jTextArea2;
    private JTextPane jTextPane1;
    private JTextPane jTextPane2;
    private JTextPane jTextPane3;
    private JTextPane jTextPane4;
    private JTextPane jTextPane5;
    private JTextPane modelEntry;
    private JLabel modelLabel;
    private JButton newAccidentButton;
    private JButton newButton;
    private JLabel numPlateLabel;
    private JTextPane ownEntry;
    private JLabel ownLabel;
    private JLabel phoneLabel;
    private JTextPane plateEntry;
    private JButton searchButton;
    private JButton updateVehicle;
    private JPanel vehicleEntry;
    private JTextPane yearEntry;
    private JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
